import logging
import time # Added for performance logging
import json # Added for JSON parsing
from typing import Optional
from bs4 import BeautifulSoup, ParserRejectedMarkup, Comment
from pydantic import ValidationError # Added for validation errors

# Import the client setup function
from .llm import get_openai_client, call_openai_extract
# Import ProductData model for type hinting (and eventually parsing)
from .models import ProductData

logger = logging.getLogger(__name__)

def _remove_tags(soup: BeautifulSoup, tags: list):
    """Helper function to remove specified tags and log the count."""
    count = 0
    for tag_name in tags:
        for tag in soup.find_all(tag_name):
            tag.decompose() # Remove the tag and its content
            count += 1
    if count > 0:
        # Log individual tag counts might be more informative
        # logger.debug(f"Removed {count} tags total from list: {tags}.")
        pass # Keep logging less verbose for now

def _remove_comments(soup: BeautifulSoup):
    """Helper function to remove HTML comments and log the count."""
    count = 0
    comments = soup.find_all(string=lambda text: isinstance(text, Comment))
    for comment in comments:
        comment.extract()
        count += 1
    if count > 0:
        logger.debug(f"Removed {count} HTML comments.")

def preprocess_html(html_content: str, parser: str = 'html.parser', prettify: bool = True) -> Optional[str]:
    """Parses, cleans, extracts main content, and formats HTML string.

    Args:
        html_content: The raw HTML string to parse.
        parser: The BeautifulSoup parser to use (e.g., 'html.parser', 'lxml').
        prettify: Whether to format the output HTML nicely (default: True).

    Returns:
        A string containing the cleaned and formatted HTML of the main content area,
        or None if parsing failed.
    """
    start_time = time.time()
    logger.debug(f"Starting HTML preprocessing using '{parser}'...")
    soup: Optional[BeautifulSoup] = None
    final_html: Optional[str] = None
    status = "Failure"

    try:
        soup = BeautifulSoup(html_content, parser)
        logger.debug("HTML parsing successful.")

        # --- HTML Cleaning (Subtask 5.2) ---
        tags_to_remove = ['script', 'style', 'meta', 'link', 'header', 'footer', 'nav', 'aside', 'form', 'iframe']
        _remove_tags(soup, tags_to_remove)
        _remove_comments(soup)
        logger.debug("HTML cleaning completed.")
        # ------------------------------------

        # --- Main Content Extraction (Subtask 5.3) ---
        content_tag_to_format = None
        content_selectors = [
            'main', '#main-content', '#content', '#product-details',
            '.product-detail', '.pdp-main-content', 'article'
        ]
        found_selector = None
        for selector in content_selectors:
            content_tag_to_format = soup.select_one(selector)
            if content_tag_to_format:
                found_selector = selector
                break

        if content_tag_to_format:
            logger.debug(f"Found main content using selector: '{found_selector}'")
        else:
            logger.warning("Could not find specific main content container. Falling back to <body>.")
            content_tag_to_format = soup.body # Use body tag
            if not content_tag_to_format:
                logger.warning("Could not find <body> tag. Falling back to whole document.")
                content_tag_to_format = soup # Fallback to whole soup
        # ---------------------------------------------

        # --- Formatting (Subtask 5.4) ---
        if content_tag_to_format:
            if prettify:
                final_html = content_tag_to_format.prettify()
            else:
                final_html = str(content_tag_to_format)
            status = "Success"
        # ----------------------------------

    except ParserRejectedMarkup as e:
        logger.error(f"HTML parsing failed (ParserRejectedMarkup): {e}")
    except Exception as e:
        logger.error(f"HTML parsing/preprocessing failed unexpectedly: {e}", exc_info=True)

    end_time = time.time()
    duration = end_time - start_time
    logger.info(f"HTML preprocessing finished. Status: {status}. Duration: {duration:.3f}s")
    return final_html

# Updated function signature and added parsing/validation logic
# Changed `processed_html` parameter name to `markdown_content` for clarity
async def extract_product_data(markdown_content: str, url: str) -> Optional[ProductData]:
    """Extracts and validates product data from cleaned MARKDOWN using an LLM.

    Args:
        markdown_content: The cleaned Markdown string generated by the crawler.
        url: The original URL of the product page.

    Returns:
        A validated ProductData object if extraction and parsing are successful,
        otherwise None.
    """
    logger.info(f"Starting LLM extraction for: {url} using Markdown")
    start_time = time.time()
    product_data: Optional[ProductData] = None

    client = get_openai_client()
    if not client:
        logger.error("OpenAI client not available for extraction.")
        return None

    # 1. Construct the messages list directly
    system_message = {
        "role": "system",
        "content": "You are an expert data extractor specializing in parsing Markdown content."
    }
    user_message_content = f"""You are an expert data extraction AI. Your task is to extract information about a Sephora product from the provided MARKDOWN content.

The URL of the page is: {url}

Please analyze the following cleaned MARKDOWN content carefully. Look for headings like \"Ingredients\" and \"How to Use\" as well as product names, prices, and image URLs.
```markdown
{markdown_content}
```

Extract the required information and format it STRICTLY as a JSON object matching the schema below.
- Provide the exact URL given above in the \"url\" field.
- For optional fields (price, currency, stock_info, image_url, description, ingredients_list, how_to_use), use `null` if the information cannot be found in the Markdown content. Do NOT guess or make up information.
- It is CRUCIAL to extract the *entire* ingredient list if present under an \"Ingredients\" heading or similar section. Do not truncate or summarize.
- Similarly, extract the *complete* \"how_to_use\" instructions if available under a relevant heading.
- Ensure the output is ONLY the JSON object, with no introductory text, explanations, or markdown formatting around it.

JSON Schema:

{{
  \"product_name\": \"string (Product's full name)\",
  \"url\": \"string (The exact URL provided: {url})\",
  \"price\": \"float | null (Numerical price, null if not found)\",
  \"currency\": \"string | null (Currency code like USD, EUR, null if not found or price is null)\",
  \"stock_info\": \"string | null (Availability status like 'In Stock', 'Out of Stock', 'Coming Soon', null if not found)\",
  \"image_url\": \"string | null (Full URL of the main product image, null if not found)\",
  \"description\": \"string | null (Product description text, null if not found)\",
  \"ingredients_list\": \"string | null (The COMPLETE list of ingredients, exactly as written. If not found, use null. Do NOT summarize or omit ingredients.)\",
  \"how_to_use\": \"string | null (The FULL instructions on how to use the product. If not found, use null.)\"
}}


Output ONLY the JSON object:"""
    user_message = {"role": "user", "content": user_message_content}
    messages = [system_message, user_message]

    # 2. Call the LLM with the messages list
    model_to_use = "gpt-4o" # Or get from config
    raw_llm_output = await call_openai_extract(messages=messages, model=model_to_use)

    # 3. Parse and Validate (Subtask 6.4)
    if raw_llm_output:
        try:
            # Attempt to parse the raw output as JSON
            # Sometimes the LLM might add markdown fences (```json ... ```)
            if raw_llm_output.strip().startswith("```json"):
                json_str = raw_llm_output.strip()[7:-3].strip() # Remove fences
            elif raw_llm_output.strip().startswith("```"):
                 json_str = raw_llm_output.strip()[3:-3].strip()
            else:
                json_str = raw_llm_output.strip()

            data_dict = json.loads(json_str)
            logger.debug(f"Successfully parsed JSON for {url}")

            # Attempt to validate the dictionary against the Pydantic model
            # This automatically checks types, required fields, and runs custom validators
            product_data = ProductData.model_validate(data_dict)
            logger.info(f"Successfully validated product data for {url}")

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM output as JSON for {url}: {e}")
            logger.debug(f"Raw LLM output that failed parsing:\n{raw_llm_output}") # Log the problematic output
        except ValidationError as e:
            logger.error(f"Pydantic validation failed for {url}: {e}")
            logger.debug(f"Parsed data dict that failed validation: {data_dict if 'data_dict' in locals() else 'N/A'}") # Log the data
        except Exception as e:
            logger.error(f"Unexpected error during parsing/validation for {url}: {e}", exc_info=True)
    else:
        logger.error(f"LLM extraction failed (no output received) for {url}.")

    end_time = time.time()
    duration = end_time - start_time
    status = "Success" if product_data else "Failure"
    logger.info(f"LLM extraction & validation finished for {url}. Status: {status}. Duration: {duration:.3f}s")

    return product_data

# Placeholder for Pinecone storage function (Task 8)
def store_product_data_pinecone(product_data_list: list):
    pass

# --- Basic Test Runner (Subtask 5.4) ---
if __name__ == '__main__':
    # Configure logging for direct script run
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

    sample_html_valid = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test Page</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css">
        <style>body { background: #fff; }</style>
    </head>
    <body>
        <header>Header Content</header>
        <nav>Navigation</nav>
        <!-- A comment -->
        <main id="main-content">
            <h1>Product Title</h1>
            <p>This is the main product description.</p>
            <div class="product-detail">
                 Price: $19.99
            </div>
            <script>alert('hello');</script>
        </main>
        <aside>Sidebar</aside>
        <footer>Footer Content</footer>
    </body>
    </html>
    """

    sample_html_no_main = """
    <!DOCTYPE html>
    <html><body><p>Just a paragraph.</p><footer>Footer</footer></body></html>
    """

    sample_html_invalid = "<html><body><p>Mismatched tag</div></html>"

    print("--- Testing Valid HTML with Main Content ---")
    result1 = preprocess_html(sample_html_valid)
    if result1:
        print("Result (Prettified):")
        print(result1)
    else:
        print("Preprocessing failed.")

    print("\n--- Testing Valid HTML without Specific Main Tag ---")
    result2 = preprocess_html(sample_html_no_main)
    if result2:
        print("Result (Prettified):")
        print(result2)
    else:
        print("Preprocessing failed.")

    print("\n--- Testing Invalid HTML ---")
    result3 = preprocess_html(sample_html_invalid)
    if result3:
        print("Result (Prettified) - Unexpected success?:")
        print(result3)
    else:
        print("Preprocessing failed as expected.")

    print("\n--- Testing Compact Output ---")
    result4 = preprocess_html(sample_html_valid, prettify=False)
    if result4:
        print("Result (Compact):")
        print(result4)
    else:
        print("Preprocessing failed.")
# -------------------------------------- 